### ISSUE TITLE
Update Palestine's list

### ISSUE THREAD

**Issue by agharbeia** [agharbeia/ooni-test-lists#2]
Update [Palestine's list](https://github.com/agharbeia/ooni-test-lists/blob/master/lists/ps.csv) to the latest known blocked websites as of the date of adding this issue.

**Comment by hannaq** [comment]
I think the .ps list is ready for a pull request now, this is all what we could find so far.

**Comment by agharbeia** [comment]
Included in the pull. Thanks, @hannaq
